#Gemfile for framework

source 'https://rubygems.org'
gem 'appium_lib'
gem 'cucumber', '3.1.2'
gem 'rake'
gem 'require_all'
gem 'rspec'
gem 'selenium-webdriver', '3.141.0'
gem 'pry'
gem 'nokogiri'
gem 'chunky_png'
gem 'data_magic'
gem 'yard-cucumber'
gem 'redcarpet'
gem 'page_navigation'
gem 'appium_console'
gem 'debase'
gem 'spreadsheet'
gem 'sauce_whisk'
gem 'childprocess'
gem 'parallel_tests'
gem 'eyes_appium'
gem 'test_object_test_result_watcher'
gem 'report_builder', '~> 1.8'
gem 'slackr'